config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "creeks#index"
  resources :creeks, only: [:show, :destroy, :new, :create, :update, :edit] do
    resources :bookings, only: [:create, :index]
  end
  resources :bookings, only: [:destroy]
  get '/mycreeks', to: 'creeks#mycreeks', as: 'mycreeks'
  get '/mycreeks/:id', to: 'creeks#mycreek', as: 'mycreek'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :creek

  # validates :date, presence: true
end

app/models/creek.rb
class Creek < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  validates :title, :country, :city, :price, :description, :capacity, :photo, presence: true
  validates :title,  uniqueness: true

  # Added for geocoding (=> address calculated based on 'city' field)
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :creeks
  has_many :bookings
  has_one_attached :photo
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, :pseudo, presence: true
  validates :email, :pseudo, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    #----
    #Code added to add a filed "pseudo" in the User table
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:pseudo])
  
      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:pseudo])
    end
    # -----
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]

    def create
        @creek = Creek.find(params[:creek_id])
        @booking = Booking.new
        @booking.user_id = current_user.id
        @booking.creek_id = @creek.id
        if @booking.save!
          redirect_to creek_bookings_path
        end
    end

    def index
        @bookings = current_user.bookings
        @creeks = Creek.joins(:bookings)
        @user = current_user.id

        # For geocoding
          @creeks_coordinates = Creek.geocoded.joins(:bookings) #return creeks with their coordinates
          @markers = @creeks_coordinates.map do |creek|
            {
              lat: creek.latitude,
              lng: creek.longitude,
              image_url: helpers.asset_url('palm-marker.png')
            }
          end
        #--- end
    end

    def destroy
        @booking = Booking.find(params[:id])
        @booking.destroy
        redirect_to creek_bookings_path(current_user.id)
    end
end

app/controllers/creeks_controller.rb
class CreeksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @creeks = Creek.all
    # For geocoding
      @creeks_coordinates = Creek.geocoded #return creeks with their coordinates
      @markers = @creeks_coordinates.map do |creek|
        {
          lat: creek.latitude,
          lng: creek.longitude,
          image_url: helpers.asset_url('palm-marker.png')
        }
      end
    #--- end
  end

  def show
    @creek = Creek.find(params[:id])
  end

  def mycreeks
    if user_signed_in?
      @user = current_user.id
      @creeks = Creek.all.where(user_id: @user)
      # For geocoding
        @creeks_coordinates = Creek.geocoded.where(user_id: @user) #return creeks with their coordinates
        @markers = @creeks_coordinates.map do |creek|
          {
            lat: creek.latitude,
            lng: creek.longitude,
            image_url: helpers.asset_url('palm-marker.png')
          }
        end
      #--- end
    else
      redirect_to '/'
    end
  end

  def mycreek
    if user_signed_in?
      @user = current_user.id
      @creek = Creek.find(params[:id])
    else
      redirect_to '/'
    end
  end

  def destroy
    @creek = Creek.find(params[:id])
    if @creek.user_id == current_user.id
      @creek.destroy
    end
    redirect_to mycreeks_path
  end

  def new
    @creek = Creek.new
  end

  def create
    @user = current_user
    @creek = Creek.new(params.require(:creek).permit(:title, :available, :country, :city, :price, :description, :capacity, :photo))
    @creek.user_id = @user.id
    if @creek.save!
      redirect_to mycreeks_path
    else
      render 'creeks/new'
    end
  end

  def edit
    @creek = Creek.find(params[:id])
  end

  def update
    @creek = Creek.find(params[:id])
    if @creek.user_id == current_user.id
      @creek.update(params.require(:creek).permit(:title, :country, :city, :available, :price, :description, :capacity, :photo))
    end
    redirect_to mycreeks_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/creeks_helper.rb
module CreeksHelper
end

app/views/bookings/index.html.erb
<!-- <% @bookings.each do |mybook| %>
    <p><%= mybook.creek.title %></p>
    <p><%= mybook.creek.country %></p>
    <p><%= mybook.creek.city %></p>
    <p><%= mybook.creek.price %>€/day</p>
    <% end %>
     -->
    
    
    <div class="whole-container">
        <div class="container-left">
            <div class="cards">
                <% @bookings.each do |mybook| %>
                <div class="card">
                    <div class="width-img">
                        <%= cl_image_tag mybook.creek.photo.key if mybook.creek.photo.attached? %>
                    </div>
                    <div class="details">
                        <h2 class="title"><%= mybook.creek.title %></h2>
                        <div class="localisation">
                            <h3 class="city"><%= mybook.creek.city %>, &nbsp</h3>
                            <h3 class="country"><%= mybook.creek.country %></h3>
                        </div>
                        <h4 class="price"><%= mybook.creek.price %>€/day</h4>
                        <div class="big-btn">
                            <%= link_to "Delete this book", booking_path(mybook), method: :delete, class: 'btn red' %>
                        </div>
                    </div>
                </div>
                <% end %>
        </div>
    </div>

    <div class="container-right">
      <div
        id="map" style="width: 90%; height: 600px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
</div>

app/views/creeks/edit.html.erb
<h1>Edit my hosting creek</h1>
<div class="form">
    <%= form_for [@creek] do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <br>
        <%= f.label :country %>
        <%= f.text_field :country %>
        <br>
        <%= f.label :city %>
        <%= f.text_field :city %>
        <br>
        <%= f.label :available? %>
        <%= f.check_box :available %>
        <br>
        <%= f.label :photo, class: 'label-photo btn', input_html: {value: 'abc'}, as: :text %>
        <%= f.file_field :photo %>
        <br>
        <%= f.submit 'Create', class: 'btn green' %>
    <% end %>
</div>

<%= link_to 'Back', mycreeks_path, class: 'btn' %>

app/views/creeks/index.html.erb
<!-- <h1>All Creeks</h1> -->
<div class="whole-container">
    <div class="container-left">
        <div class="cards">
            <% @creeks.each do |creek| %>
                <div class="card">
                    <div class="width-img">
                        <%= cl_image_tag creek.photo.key if creek.photo.attached? %>
                    </div>
                    <div class="details">
                        <h2 class="title"><%= creek.title %></h2>
                        <div class="localisation">
                            <h3 class="city"><%= creek.city %>, &nbsp</h3>
                            <h3 class="country"><%= creek.country %></h3>
                        </div>
                        <h4 class="price"><%= creek.price %>€/day</h4>
                        <div class="big-btn">
                            <%= link_to "Show", creek_path(creek), class: "btn" %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>

    <div class="container-right">
      <div
        id="map" style="width: 90%; height: 600px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
</div>

app/views/creeks/mycreek.html.erb
<!-- <div class="unique-card">
    <%= cl_image_tag @creek.photo.key, width: 400, height: 300, crop: :fill if @creek.photo.attached? %>
    <h1><%= @creek.title %></h1>
    <h3><%= @creek.country %></h3>
    <h3><%= @creek.city %></h3>
    <h4><%= @creek.price %></h4>
    <p><%= @creek.description %></p>
    <h3><%= @creek.capacity %></h3>
</div>

<%= link_to 'Back', mycreeks_path %> -->

<div class="show-container">
    <h1>Details of the <%= @creek.title %></h1>
    <div class="unique-card" style="margin-bottom: 20px;">
        <div class="width-img">
            <%= cl_image_tag @creek.photo.key if @creek.photo.attached? %>
        </div>
        <div class="details-singlecard">
            <h4 class="price"><%= @creek.price %>€/day</h4>
            
            <p class="description"><strong>Description: </strong><em><%= @creek.description %></em></p>
            <div class="localisation">
                <h3 class="city"><%= @creek.city %>, &nbsp;</h3>
                <h3 class="country"><%= @creek.country %></h3>
            </div>
            <% if @creek.available %>
            <h3 class="available">Available</h3>
            <% else %>
            <h3 class="available">Not available</h3>
            <% end %>
            <h3 class="capacity"><span>Capacity: </span><%= @creek.capacity %> persons</h3>
        </div>
    </div>
</div>

<%= link_to 'Back', mycreeks_path, class: 'btn' %>

app/views/creeks/mycreeks.html.erb
<div class="whole-container">
    <div class="container-left">
        <p><%= link_to "Add a new hosting creek", new_creek_path, class: 'btn btn-add-creek' %></p>
        <div class="cards">
            <% @creeks.each do |creek| %>
                <div class="card">
                    <%= cl_image_tag creek.photo.key if creek.photo.attached? %>
                    <div class="details">
                        <h2 class="title"><%= creek.title %></h2>
                        <div class="localisation">
                            <h3 class="city"><%= creek.city %>, &nbsp</h3>
                            <h3 class="country"><%= creek.country %></h3>
                        </div>
                        <h4 class="price"><%= creek.price %>€/day</h4>
                        <div class="big-btn display-btns">
                            <p><%= link_to "Show", mycreek_path(creek), class: 'btn pink' %></p>
                            <p><%= link_to "Edit", edit_creek_path(creek), class: 'btn green' %></p>
                            <p><%= link_to "Delete", creek_path(creek), method: :delete, data: {confirm: 'Are you really really sure?'}, class: 'btn red-two' %></p>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>

    <div class="container-right">
      <div
        id="map" style="width: 90%; height: 600px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
  
</div>

app/views/creeks/new.html.erb
<h1>New hosting creek</h1>
<div class="my-form">
    <%= form_for [@creek] do |f| %>
        <div class="field">
            <%= f.label :title %>
            <%= f.text_field :title,  placeholder: "Title" %>
        </div>
        <br>
        <div class="field">
            <%= f.label :country %>
            <%= f.text_field :country,  placeholder: "Country" %>
        </div>
        <br>
        <div class="field">
            <%= f.label :city %>
            <%= f.text_field :city,  placeholder: "City" %>
        </div>
        <br>
        <div class="field">
            <%= f.label :Available? %>
            <p><%= f.check_box :available,  placeholder: "Available?" %></p>
        </div> 
        <br>
        <div class="field">
            <%= f.label :price %>
            <%= f.text_field :price,  placeholder: "Price" %>
        </div>
        <br>
        <div class="field">
            <%= f.label :capacity %>
            <%= f.text_field :capacity,  placeholder: "Capacity" %>
        </div>
        <br>
        <div class="field">
            <%= f.label :description %>   
            <%= f.text_area :description,  placeholder: "Description" %>
        </div>
        <br>
        <div class="container-photo">
            <div class="field">
                <%= f.label :photo, class:"photo" %>
                <%= f.file_field :photo %>
            </div>
        </div>
        <br>
        <div class="submit">
        <%= f.submit %>
        </div>
    <% end %>
</div>

app/views/creeks/show.html.erb
<div class="show-container">
    <h1>Details of <%= @creek.title %></h1>
    <div class="unique-card" style="margin-bottom: 20px;">
        <div class="width-img">
            <%= cl_image_tag @creek.photo.key if @creek.photo.attached? %>
        </div>
        <div class="details-singlecard">
            <h4 class="price"><%= @creek.price %>€/day</h4>
            
            <p class="description"><strong>Description: </strong><em><%= @creek.description %></em></p>
            <div class="localisation">
                <h3 class="city"><%= @creek.city %>, &nbsp;</h3>
                <h3 class="country"><%= @creek.country %></h3>
            </div>
            <h3 class="capacity"><span>Capacity: </span><%= @creek.capacity %> persons</h3>
            <% if @creek.available %>
            <h3 class="available">Available</h3>
            <%= link_to "Book !", creek_bookings_path(@creek), method: :post, class: "btn book" %>
            <% else %>
            <h3 class="available">Not available</h3>
            <%= link_to "Book !", creek_bookings_path(@creek), method: :post, class: "btn book pointer" %>
            <% end %>
        </div>
    </div>
    <%= link_to 'Back', '/', class: 'btn btn-back' %>
</div>

app/views/layouts/_header_co.html.erb
<header>
    <a class="logo" href="/" class="btn btn-primary">Creeks.</a>
    <input type="text" placeholder="Search by city ..." id="search-bar">
    <nav>
        <ul>
            <li><%= link_to "My bookings", creek_bookings_path(current_user.id) %></li>
            <li><%= link_to "My creeks", mycreeks_path %></li>
            <li><%= link_to "My profile", edit_user_registration_path %></li>
            <li><%= link_to "Disconnect", destroy_user_session_path, method: :delete %></li>
        </ul>
    </nav>
</header>

app/views/layouts/_header_deco.html.erb
<header>
    <a class="logo" href="/">Creeks.</a>
    <input type="text" placeholder="Search ..." id="search-bar">
    <nav>
        <ul>
            <li><%= link_to "Connect", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
        </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>CreekApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
    <% if user_signed_in? %>
    <%= render 'layouts/header_co' %>
    <% else %>
    <%= render 'layouts/header_deco' %>
    <% end %>

    <div class="container">
      <div class="containers">
          <%= yield %>
      </div>
    </div>
  <%= javascript_pack_tag "application" %> 
  </body>
</html>